-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('GERANT', 'RESPONSABLE_GENERAL', 'RESPONSABLE_PRODUCTION', 'RESPONSABLE_LIVRAISON', 'RESPONSABLE_FINANCIER_STOCKS');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role" "UserRole" NOT NULL DEFAULT 'RESPONSABLE_PRODUCTION';
