export const INVOICE_DOCUMENT_PREVIEW_LABELS = {
  logoPlaceholder: 'Logo',
  siretPrefix: 'SIRET',
  vatPrefix: 'TVA',
  defaultClientLabel: 'Facturé à',
  metaInvoiceNumber: 'N°',
  metaIssueDate: 'Émise le',
  metaDueDate: 'Échéance',
  metaOrderReference: 'Commande',
  metaCurrency: 'Devise',
  columnDescription: 'Description',
  columnQuantity: 'Qté',
  columnUnitPriceHt: 'P.U. HT',
  columnTaxRate: 'TVA',
  columnLineTotalHt: 'Total HT',
  totalSubtotalHt: 'Sous-total HT',
  totalTaxAmount: 'TVA',
  totalTtc: 'Total TTC',
  totalPaidAmount: 'Déjà réglé',
  ibanLabel: 'IBAN',
  documentTitle: 'Aperçu facture',
} as const;

export const INVOICE_TYPE_TITLES = {
  PROFORMA: 'Facture proforma',
  DEPOSIT: 'Facture d\'acompte',
  INTERMEDIATE: 'Facture intermédiaire',
  FINAL: 'Facture',
  CREDIT_NOTE: 'Avoir',
} as const;

export const MOCK_INVOICE_DOCUMENT_PREVIEW = {
  companyName: 'Raphia Atelier SARL',
  companyAddress: '12 rue des Tisserands\n34000 Montpellier\nFrance',
  siret: '123 456 789 00012',
  vatNumber: 'FR12 123456789',
  iban: 'FR76 3000 6000 0112 3456 7890 189',
  cgvText: 'Paiement à 30 jours. Pénalités de retard : 3× taux légal.',
  clientName: 'Maison Déco Demo',
  clientAddress: '8 avenue du Commerce\n75010 Paris\nFrance',
  contactName: 'Camille Martin',
  invoiceNumber: 'FAC-2026-0001',
  invoiceTitle: 'Facture',
  issueDate: '15/07/2026',
  dueDate: '14/08/2026',
  orderReference: 'CMD-2026-0142',
  currency: 'EUR',
  invoiceNotes: 'Livraison prévue semaine 30.',
  lines: [
    {
      description: 'Panier raphia M — naturel',
      quantity: '24',
      unitPriceHt: '12,50',
      taxRate: '20 %',
      lineTotalHt: '300,00',
    },
    {
      description: 'Set de table tressé',
      quantity: '10',
      unitPriceHt: '8,00',
      taxRate: '20 %',
      lineTotalHt: '80,00',
    },
  ],
  subtotalHt: '380,00',
  taxAmount: '76,00',
  totalTtc: '456,00',
  paidAmount: '0,00',
} as const;
